### ISSUE TITLE
No Lenovo Models found

### ISSUE THREAD

**Issue by CalvinistNerd** [maurice-daly/DriverAutomationTool#159]
Gives the following warning:  No Lenovo models found.  If you are using a proxy server please specify the proxy in the Proxy Server Settings tab.  

Except, the proxy server settings are correct.

**Comment by athmanb** [comment]
According to the process log file, it tries to download a https://download.lenovo.com/cdrt/td/catalogv2.html but if you try to access that URL you get a 404 error. So this seems to happen because Lenovo moved the file.
Unfortunately the directory https://download.lenovo.com/cdrt/td/ doesn't allow file listing so I can't see where they moved the file to.

**Comment by DaveBobFred** [comment]
The correct link is the xml file which does resolve when using [https://download.lenovo.com/cdrt/td/catalogv2.xml](url)

This still causes issues with getting Lenovo info for myself as I get the **Found: 0 known Lenovo models**

**Comment by CalvinistNerd** [comment]
Agreed.  This issue appears to be resolved in the 6.5 beta version.  Lenovo models were listed after upgrading to that version.
