### ISSUE TITLE
7.0.0 - Error in log when starting

### ISSUE THREAD

**Issue by nodiaque** [maurice-daly/DriverAutomationTool#287]
Hello,

I get these messages when starting the 7.0.0 version in the console

`Import-Module : Le module « Az.Accounts » spécifié n'a pas été chargé, car aucun fichier de module valide n'a été trouvé dans un répertoire de module.
Au caractère Ligne:16112 : 2
+     Import-Module -Name Az.Accounts
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Az.Accounts:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Import-Module : Le module « Az.Storage » spécifié n'a pas été chargé, car aucun fichier de module valide n'a été trouvé dans un répertoire de module.
Au caractère Ligne:16113 : 2
+     Import-Module -Name Az.Storage
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Az.Storage:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
 
`

**Comment by rtruss** [comment]
I just updated to 7.0.1 and noticed that the Azure messages no longer appear, so looks to be resolved.  LOL I do get this now though:

Get-Content : Cannot find path 'C:\DriverAutomationTool\Prod\Temp\DriverPackCatalog.xml' because it does not exist.
At line:16548 char:34

I have a cab file and a catalogPC.xml file in there

If I manually extract the xml file from the cab file all is well.
