### ISSUE TITLE
Dell Drivers no longer able to extract

### ISSUE THREAD

**Issue by Ru66erDucky** [maurice-daly/DriverAutomationTool#353]
Using 7.0.4 and also tried 7.1.1 Dell driver no longer extract.  It seems Dell changed from CAB to EXE and doesn't know how to extract driver now.  Models impacted are Latitude 9420 and 9430.

**Comment by WhaleOfATimeProductions** [comment]
I'm seeing the same issue with the Latitude 7420. 

It seems to relate the 2GB .CAB file limit mentioned on this page within Dell's support site:
https://www.dell.com/support/kbdoc/en-uk/000197955/file-format-change-of-dell-command-deploy-driver-pack-from-cab-to-dup

Using the command "7420-p5m13_win10_1.0_a09.exe /s /e=_d:\LocationToExtractFiles_ 
extracts the files usually found within the CAB files. It totals ~3.2GB 

I've then gone through the process of creating a custom package for the device using the details that were applied to the package previously created. 

Looking at the catalogue there are a number of Dell devices which have now switched to the DUP .exe format so this issue is likely to grow. Here is an image of the 7420 entry within the catalogue, I've also checked online for the latest catalogue driver pack and it is the file listed. 

![Dell - Driver Catalogue - Latitude 7420](https://user-images.githubusercontent.com/17208676/173061006-92b1f3b8-4963-4c50-946c-c94f53d3773d.PNG)

**Comment by WhaleOfATimeProductions** [comment]
This is the first time I'm using the custom package creation process so I may be doing something wrong, but it doesn't seem to respect the settings we use for the automated driver update import process. Deployment Platform is set as "ConfigMgr".

For example we use .WIM files as containers for the drivers to avoid copying lots of individual files, and have the folder structure within MECM as follows, but instead the custom package is placed in the root Packages folder:
Packages -> Driver Packages -> Dell

Is this expected behaviour or is there a way to force the custom packages to conform to the settings enabled in ConfigMgr Settings tab?

**Comment by Ru66erDucky** [comment]
What I did so far is to extract the files manually place in the catalog folder where it suppose to extract, and re-run the job.  That actually moves the files, and created the standardpkg for me.  However, the version # is messed up.  It is showing the model # now instead of the CAB version.  I am not using WIM format - still using just files, and have not validate dynamic driver is working or not.  Someone else mention issue with the WIM file created, and they had to mount the WIM and correct versioning.  Hope this help - https://github.com/maurice-daly/DriverAutomationTool/issues/351

**Comment by WhaleOfATimeProductions** [comment]
The trick of putting the files in the source folder is good to know, thanks for sharing. I've tested the manual package I created and can confirm that is working during the imaging process.

Regarding the version number issue you mentioned, I saw that same issue for the 7420 and it looks like Dell have used the model number instead of driver pack version in the catalogue as well as the knowledge page. 

I expect if you compare a .cab entry in the catalogue XML file I mentioned above with the .exe entry you could work out which property needs editing to the correct version number to fix this issue. I've successfully modified the XML file in the past when dell mixed up the download links for .cab files.

**Comment by TazwellJ** [comment]
Seeing the same issues.  Both with the .exe packages and the incorrect version naming.

**Comment by WhaleOfATimeProductions** [comment]
It looks like Maurice has uploaded a new beta version of the tool with fixes for the Dell packages. 

Has anyone already tried version 7.1.2?
![image](https://user-images.githubusercontent.com/17208676/173377184-26131f56-2ebd-413f-a6b7-2ecda8154ad5.png)

**Comment by TazwellJ** [comment]
Not yet but about to download it now.

**Comment by WhaleOfATimeProductions** [comment]
Thanks for testing, I'll hopefully get round to updating it in our environment Tuesday/Wednesday. Big thanks to the Devs as always!

**Comment by carvius87** [comment]
Hi everyone,
i also installed 7.1.2 beta and now everything works fine. Modellnumber is Ok and the Packages looking good. A testinstallation was succesful.

BR

**Comment by hudyscott** [comment]
So I figured it out....Not ALL the dell drivers/bios are converted to DUP....So I used MSEndPointMgr v6.4.9 & was able to download, extract, and package that I needed to.....

**Comment by DewayneHyatt** [comment]
Dell corrected the error in their xml regarding the 5530. I was able to use DAT to download and extract (still running 7.5.1 beta). The updated catalog is back to cab files for the 5530 rather than exe.

**Comment by hudyscott** [comment]
Great, thx

Hudy Scott
PC Technician
CURO Financial Technologies Corp
t. 316.425.1330
c. 316.706.7187

**Comment by MiketheMaker18** [comment]
Still having this issue in 7.1.7. @maurice-daly are you going to wait on Dell to fix this or plan to figure out some sort of if-then for cab vs exe? Thank you!

**Comment by MiketheMaker18** [comment]
> 

It's just the extraction process. If DAT doesn't see a CAB file after the download and before extraction, run exe extraction command before the ps import step. Shouldn't be too hard to program that in, but with that said I haven't had time either.

**Comment by hudyscott** [comment]
I agree but there was no file.....at least on the one I was working on....

Hudy Scott
IT Technician | Community Choice Financial
Direct: 316-425-1330
***@***.******@***.***>
PLEASE NOTE:  Speedy Cash, Rapid Cash and Avio are now part
of the Community Choice Financial family of companies
[cid:43b11ffc-1508-4545-989f-dc7b1936575c]
________________________________
From: Mike Pluff ***@***.***>
Sent: Wednesday, September 7, 2022 10:56 AM
To: maurice-daly/DriverAutomationTool ***@***.***>
Cc: hudyscott ***@***.***>; Comment ***@***.***>
Subject: [External]Re: [maurice-daly/DriverAutomationTool] Dell Drivers no longer able to extract (Issue #353)


CAUTION: External Email
This email has originated from outside of the organization. Do not click any links or open any attachments unless you have verified the sender and know the content is safe.

CAUTION: This email was sent from outside the organization ***@***.***). Do not click links or open attachments unless you recognize the sender and know the content is safe.

It's just the extraction process. If DAT doesn't see a CAB file after the download and before extraction, run exe extraction command before the ps import step. Shouldn't be too hard to program that in, but with that said I haven't had time either.

**Comment by MiketheMaker18** [comment]
Hmm that's odd. Using 7.1.7 (issue started for me i think 7.1.2), it's either downloading the CAB or EXE (Dell models), but when it extracts the EXE to the extraction folder, it just copies the EXE instead of actually extracting it. It shows success when importing into MDT, but obviously MDT won't import an exe as drivers. I've just been manually extracting the EXE's and importing them.

**Comment by agbrint** [comment]
Using >7.1.7 I am able to pull down the newer EXE files and successfully extract them, however we (multiple groups running independent CM/DAT installs) are seeing a pop-up security dialog relating to the extraction of the files on Windows Server 2019 systems.  Selecting OK at the prompt will successfully extract the files as expected and continue on with the process, successfully creating a driver package.  Selecting Cancel at the prompt will not extract the files and attempt to create a 0k package (which fails to distribute or install drivers).
My best guess without digging into the code myself is that it's running in a separate process which is not inherently "elevated" such as the DAT exe is on our systems.  Options such as lowering or disabling UAC not an option in our environments.

**Comment by maurice-daly** [comment]
Unfortunately this is due to a change in the way Dell provides the driver packages. Today they are delivered in priority EXE format. The new version of the tool can extract these however.

**Comment by hudyscott** [comment]
Thanks for the info & you hit the nail on the head about dell.
I'm looking for the win10 drivers & not the Win11 drivers.....
How did you get/find the correct Win11 driver path?


Hudy Scott
PC Technician
CURO Financial Technologies Corp
t. 316.425.1330
c. 316.706.7187
