### ISSUE TITLE
No surface drivers found for Windows 10 22H2 (Build 10945)

### ISSUE THREAD

**Issue by bradlsi01** [maurice-daly/DriverAutomationTool#491]
There seem to be no Windows 10 22H2 Surface drivers in the JSON.  As we have just moved to that as our default build version it's causing a few problems.  Is there a way round this?  I don't really want to have to mess around with the deployment scripts :-(

**Comment by Swelidingo** [comment]
none of the surface pro 9 links are working

**Comment by Swelidingo** [comment]
To get this resolved i had to edit the OEMlinks.xml file under the settings folder. i created a new xml file under my github and created new links to point to microsoft with the drivers for the microsoft surface 9 pro. when you start the driver tool just search for Surface_Pro_9

anyone interested just make a backup and replace the microsoft links part with the below 

</Manufacturer>
		<Manufacturer Name="Microsoft" >
		<Link Type="XMLSource" URL="https://raw.githubusercontent.com/Swelidingo/driverAutomationTool/main/MSProducts.xml"></Link>
		<Link Type="JSONSource" URL="https://raw.githubusercontent.com/Swelidingo/driverAutomationTool/main/OSDCatalogMicrosoftDriverPack.json"></Link>
		<Link Type="BaseURL" URL="https://aka.ms/"></Link>
		<Link Type="SurfaceDriverSupportURL" URL="https://download.microsoft.com/download/e/9/a/e9a35d1b-7b4c-48d4-8619-5301d4c09f65"></Link>
	</Manufacturer>

**Comment by Latiron** [comment]
Does this include all other Microsoft Surface devices for Windows 11 22H2 and Windows 10 22H2?

**Comment by Swelidingo** [comment]
Nope. I only added the surface pro 9

**Comment by Latiron** [comment]
Well, thanks for this info.  Doesn't really help us out but for the one model.  These developers need to get on the ball and get this fixed asap.  It's crazy they haven't even looked over this to fix the issue. and it's not like 22H2 is a new release.  What happens when 23H1 or 23H2 is released?  When you come to depend on a product and it's not updated regularly, your environment suffers.  I could even see paying for this product if it had full support behind it.  So the donation link on this pages github site is a joke.  Who'd donate if they aren't caring enough to update their product?  Ugh.  So frustrated!

**Comment by Latiron** [comment]
Thank you sir.  This would be a good work around if all the models we use were listed with Windows 11 22H2 drivers.  We have many more than what I found in the file.  It would work for our SP9 models.  But we also added in the fallback line so that it would try and use the 21H2 drivers.  So far this seems to have fixed that issue, but I'm not confident this is a long term solution.
Also, I'm not stating I expect you or anyone else outside of the developers of this application, to go in and update all the models to work with 22H2 natively.  But thank you again for the reply and file.
