### ISSUE TITLE
DAT being Flagged as Wildfire Malware

### ISSUE THREAD

**Issue by Mrgreen17** [maurice-daly/DriverAutomationTool#7]
Infosec will not let me install DAT 6.4.6.0 anymore. is there anyway we can get this verified

**Comment by Mrgreen17** [comment]
can we get new MD5 hashes

**Comment by maurice-daly** [comment]
Unfortunately the issue is someone started sharing copies with a serial generator for the tool (http://insesilest.over-blog.com/2020/03/Driver-Automation-Tool-643-Crack-Serial-key-Latest-2020.html) obviously including malware. This sent AV detection's my way...

I'll post the MD5 hashes today for you.
