### ISSUE TITLE
Dell Bios download

### ISSUE THREAD

**Issue by AsmusRohwer** [maurice-daly/DriverAutomationTool#77]
Hello,

i´m not sure if this is an issue by DAT but if i download the Bios of an Dell Latitude E5570 i only get Version 1.15.4
but at the dell support site there are version 1.22.3 ready for download.
and i do not understand why the DAT only find the older version.

**Comment by agrooms** [comment]
Seems common with all vendors.  I am thinking the Bios and Driver packages are not updated but a few times a years, whereas the discrete drivers and bios are updated more frequently.  Just my theory.

**Comment by AsmusRohwer** [comment]
but if i use the "Third-Party Software Update Catalog" from Dell in SCCM: https://downloads.dell.com/Catalog/DellSDPCatalogPC.cab
the SCCM found also the new bios.
it seems there are two different catalogs.
one for "normal" use: https://downloads.dell.com/catalog/CatalogPC.cab
and the one for sccm and wsus: https://downloads.dell.com/Catalog/DellSDPCatalogPC.cab

maybe there is a way to use the second ?

**Comment by agrooms** [comment]
Good question.  I see that as well.  Sadly I don't know the answer 😢

**Comment by agrooms** [comment]
I ended up hitting it again and now I am getting updated drivers for MANY Dell models (3050, 7400, 7580, 7490, 3040, 7060, 7070 and 3070.

**Comment by nodiaque** [comment]
Getting the same problem for the Precision 3630. It pulled an older bios from the website:
https://www.dell.com/support/home/en-us/product-support/product/precision-3630-workstation/drivers

Version pulled is 2.1.2 while there's 2.6.1 available for at least 2 months.

**Comment by ncsutmf** [comment]
Noticed issues with the Optiplex 9010 BIOS, it was downloading A25 while at some previous point it had downloaded A30.  Although the code has changed since then, this appears related to #37 

Also found an extra closing bracket on line 15507 in the Invoke-Downloads function that was causing the script to not run (if you run the latest .PS1 directly instead of the .exe).

The issue appears to be when the catalog contains multiple matching entries in a number of places, it is sorting by release date (Ascending by default) and then selecting the first one, which is the oldest and not the newest item in the catalog.  Explicitly adding the `-Descending` switch to the Sort-Object statements in the Find-DellBios function appears to fix this.  Those statements are in multiple places in the function, currently lines 12929, 12935, 12939, 12948, 12952, and 12957.

**Comment by AsmusRohwer** [comment]
You got it men! made my day. Thanks.
This is the solution.

**Comment by MJPhelan** [comment]
Related: The XML file used by the Driver Automation Tool only grabs what's available through the Dell command | Deploy Driver cabs - https://www.dell.com/support/article/en-us/sln312414/dell-command-deploy-driver-packs-for-enterprise-client-os-deployment?lang=en - These are usually updated on the 2nd Tuesday of the month. - The product page for any given machine is updated far more frequently. Which _may_  contribute to the issue you are seeing.

So in addition to the XML file being a pain to parse, often it's just badly out of date... - Which is down to Dell to fix I'm afraid.

**Comment by maurice-daly** [comment]
> Related: The XML file used by the Driver Automation Tool only grabs what's available through the Dell command | Deploy Driver cabs - https://www.dell.com/support/article/en-us/sln312414/dell-command-deploy-driver-packs-for-enterprise-client-os-deployment?lang=en - These are usually updated on the 2nd Tuesday of the month. - The product page for any given machine is updated far more frequently. Which _may_ contribute to the issue you are seeing.
> 
> So in addition to the XML file being a pain to parse, often it's just badly out of date... - Which is down to Dell to fix I'm afraid.

Indeed sometimes the challenge is just what the tool is being fed from the manufacturer, and their own processes to update the source files.
