### ISSUE TITLE
Issue with upgrade of DriverAutomationToolSetup.msi

### ISSUE THREAD

**Issue by ps959** [maurice-daly/DriverAutomationTool#91]
I've downloaded the install files and when I open DriverAutomationTooolSetup.msi I get an error "Another version of this product is already installed. Installation of this version cannot continue. Remove existing version of this product..."

I remember running the upgrade process of a few months ago with no issues. Am I doing something wrong?

**Comment by joneess** [comment]
You're supposed to uninstall the existing version first, then install the new version

**Comment by ps959** [comment]
> You're supposed to uninstall the existing version first, then install the new version

Will this wipe out all my settings?

**Comment by MikeDFW** [comment]
> > You're supposed to uninstall the existing version first, then install the new version
> 
> Will this wipe out all my settings?

@ps959 Did you figure this out? I'm also afraid to uninstall and lose my settings.

**Comment by MikeDFW** [comment]
I made a copy of my Driver Automation Tool folder, uninstalled 6.4.6 and then installed 6.4.8. The new version went into C:\Program Files\MSEndpintMgr instead of Program Files\SCConfigMgr. So, I copied my settings folder from the old location to the new location.  However, now I'm getting the following error when trying to get the HP Catalog: 

Error: The 'Start-BitsTransfer' command was found in the module 'BitsTransfer', but the module could not be loaded

**Comment by MikeDFW** [comment]
Fixed the 'Start-BitsTransfer' issue by copying DriverAutomationTool.exe.config from the old DAT folder to the new one

**Comment by maurice-daly** [comment]
The issue was due to the change in installation directory, from SCConfigMgr to MSEndpointMgr. Unfortunately I couldnt see a clean method without requiring additional scripting. The settings file can be copied in from the old location though
